version: "3"
services:
    httpd:
      container_name: httpd
      image: httpd
      ports:
        - 80
      env_file:
        - ../../.env
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_AGENT_NAME=httpd
        - DT_AGENT_COLLECTOR=${DT_COLLECTOR_NAME}
      command: >
        sh -c " \
          ${DT_HOME}/run-wsagent.sh && \
          (echo LoadModule dtagent_module ${DT_HOME}${AGENT_LIB64} >> conf/httpd.conf) && \
          httpd-foreground"

volumes:
  agentdata:
    external: true

networks:
    default:
        external:
            name: dynatracedocker_appmon
